# Generated by Django 4.2.3 on 2023-09-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_details',
            name='sub_branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankapp.sub_branch'),
            preserve_default=False,
        ),
    ]
