# Generated by Django 4.2.3 on 2023-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_cust_details_sub_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_details',
            name='dob',
            field=models.DateField(),
        ),
    ]
